### ISSUE TITLE
Stackage build failure for yoga-0.0.0.4

### ISSUE THREAD

**Issue by alexeyzab** [Mokosha/yoga-hs#2]
As seen on the build server:

```
Preprocessing library for yoga-0.0.0.4..
Building library for yoga-0.0.0.4..
[1 of 3] Compiling Bindings.Yoga    ( dist/build/Bindings/Yoga.hs, dist/build/Bindings/Yoga.o )
[2 of 3] Compiling Bindings.Yoga.Enums ( dist/build/Bindings/Yoga/Enums.hs, dist/build/Bindings/Yoga/Enums.o )
[3 of 3] Compiling Yoga             ( lib/Yoga.hs, dist/build/Yoga.o )

In file included from /usr/include/c++/5/array:35:0: error:
    0,
                     from yoga/Yoga-internal.h:10,
                     from yoga/YGConfig.h:9,
                     from yoga/YGNode.h:10,
                     from yoga/Utils.h:9,
                     from yoga/Utils.cpp:8:

/usr/include/c++/5/bits/c++0x_warning.h:32:2: error:
     error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
     #error This file requires compiler and library support \
      ^
   |
32 | #error This file requires compiler and library support \
   |  ^

In file included from yoga/Yoga-internal.h:13:0: error:
    0,
                     from yoga/YGConfig.h:9,
                     from yoga/YGNode.h:10,
                     from yoga/Utils.h:9,
                     from yoga/Utils.cpp:8:

yoga/Yoga.h:456:10: error:
     error: ‘std::function’ has not been declared
         std::function<void(YGNodeRef node)>&& f);
              ^
    |
456 |     std::function<void(YGNodeRef node)>&& f);
    |          ^

yoga/Yoga.h:456:18: error:
     error: expected ‘,’ or ‘...’ before ‘<’ token
         std::function<void(YGNodeRef node)>&& f);
                      ^
    |
456 |     std::function<void(YGNodeRef node)>&& f);
    |                  ^

In file included from yoga/YGConfig.h:9:0: error:
    0,
                     from yoga/YGNode.h:10,
                     from yoga/Utils.h:9,
                     from yoga/Utils.cpp:8:

yoga/Yoga-internal.h:15:7: error:
     error: expected nested-name-specifier before ‘YGVector’
     using YGVector = std::vector<YGNodeRef>;
           ^
   |
15 | using YGVector = std::vector<YGNodeRef>;
   |       ^

yoga/Yoga-internal.h:47:19: error:
     error: ‘array’ in namespace ‘std’ does not name a template type
     extern const std::array<YGEdge, 4> trailing;
                       ^
   |
47 | extern const std::array<YGEdge, 4> trailing;
   |                   ^

yoga/Yoga-internal.h:48:19: error:
     error: ‘array’ in namespace ‘std’ does not name a template type
     extern const std::array<YGEdge, 4> leading;
                       ^
   |
48 | extern const std::array<YGEdge, 4> leading;
   |                   ^

yoga/Yoga-internal.h:56:16: error:
     error: ‘array’ in namespace ‘std’ does not name a template type
         const std::array<YGValue, size> val1,
                    ^
   |
56 |     const std::array<YGValue, size> val1,
   |                ^

yoga/Yoga-internal.h:56:21: error:
     error: expected ‘,’ or ‘...’ before ‘<’ token
         const std::array<YGValue, size> val1,
                         ^
   |
56 |     const std::array<YGValue, size> val1,
   |                     ^
yoga/Yoga-internal.h: In function ‘bool YGValueArrayEqual(int)’:

yoga/Yoga-internal.h:60:29: error:
     error: ‘val1’ was not declared in this scope
         areEqual = YGValueEqual(val1[i], val2[i]);
                                 ^
   |
60 |     areEqual = YGValueEqual(val1[i], val2[i]);
   |                             ^

yoga/Yoga-internal.h:60:38: error:
     error: ‘val2’ was not declared in this scope
         areEqual = YGValueEqual(val1[i], val2[i]);
                                          ^
   |
60 |     areEqual = YGValueEqual(val1[i], val2[i]);
   |                                      ^
yoga/Yoga-internal.h: At global scope:

yoga/Yoga-internal.h:118:16: error:
     error: ‘array’ in namespace ‘std’ does not name a template type
         const std::array<YGValue, YGEdgeCount>& edges,
                    ^
    |
118 |     const std::array<YGValue, YGEdgeCount>& edges,
    |                ^

yoga/Yoga-internal.h:118:21: error:
     error: expected ‘,’ or ‘...’ before ‘<’ token
         const std::array<YGValue, YGEdgeCount>& edges,
                         ^
    |
118 |     const std::array<YGValue, YGEdgeCount>& edges,
    |                     ^

In file included from yoga/YGNode.h:10:0: error:
    0,
                     from yoga/Utils.h:9,
                     from yoga/Utils.cpp:8:

yoga/YGConfig.h:13:8: error:
     error: ‘array’ in namespace ‘std’ does not name a template type
       std::array<bool, YGExperimentalFeatureCount> experimentalFeatures;
            ^
   |
13 |   std::array<bool, YGExperimentalFeatureCount> experimentalFeatures;
   |        ^

In file included from yoga/YGNode.h:11:0: error:
    0,
                     from yoga/Utils.h:9,
                     from yoga/Utils.cpp:8:

yoga/YGLayout.h:13:8: error:
     error: ‘array’ in namespace ‘std’ does not name a template type
       std::array<float, 4> position;
            ^
   |
13 |   std::array<float, 4> position;
   |        ^

yoga/YGLayout.h:14:8: error:
     error: ‘array’ in namespace ‘std’ does not name a template type
       std::array<float, 2> dimensions;
            ^
   |
14 |   std::array<float, 2> dimensions;
   |        ^

yoga/YGLayout.h:15:8: error:
     error: ‘array’ in namespace ‘std’ does not name a template type
       std::array<float, 6> margin;
            ^
   |
15 |   std::array<float, 6> margin;
   |        ^

yoga/YGLayout.h:16:8: error:
     error: ‘array’ in namespace ‘std’ does not name a template type
       std::array<float, 6> border;
            ^
   |
16 |   std::array<float, 6> border;
   |        ^

yoga/YGLayout.h:17:8: error:
     error: ‘array’ in namespace ‘std’ does not name a template type
       std::array<float, 6> padding;
            ^
   |
17 |   std::array<float, 6> padding;
   |        ^

yoga/YGLayout.h:30:8: error:
     error: ‘array’ in namespace ‘std’ does not name a template type
       std::array<YGCachedMeasurement, YG_MAX_CACHED_RESULT_COUNT>
            ^
   |
30 |   std::array<YGCachedMeasurement, YG_MAX_CACHED_RESULT_COUNT>
   |        ^

yoga/YGLayout.h:32:8: error:
     error: ‘array’ in namespace ‘std’ does not name a template type
       std::array<float, 2> measuredDimensions;
            ^
   |
32 |   std::array<float, 2> measuredDimensions;
   |        ^

In file included from yoga/YGNode.h:12:0: error:
    0,
                     from yoga/Utils.h:9,
                     from yoga/Utils.cpp:8:

yoga/YGStyle.h:14:9: error:
     error: expected nested-name-specifier before ‘Dimensions’
       using Dimensions = std::array<YGValue, 2>;
             ^
   |
14 |   using Dimensions = std::array<YGValue, 2>;
   |         ^

yoga/YGStyle.h:30:8: error:
     error: ‘array’ in namespace ‘std’ does not name a template type
       std::array<YGValue, YGEdgeCount> margin;
            ^
   |
30 |   std::array<YGValue, YGEdgeCount> margin;
   |        ^

yoga/YGStyle.h:31:8: error:
     error: ‘array’ in namespace ‘std’ does not name a template type
       std::array<YGValue, YGEdgeCount> position;
            ^
   |
31 |   std::array<YGValue, YGEdgeCount> position;
   |        ^

yoga/YGStyle.h:32:8: error:
     error: ‘array’ in namespace ‘std’ does not name a template type
       std::array<YGValue, YGEdgeCount> padding;
            ^
   |
32 |   std::array<YGValue, YGEdgeCount> padding;
   |        ^

yoga/YGStyle.h:33:8: error:
     error: ‘array’ in namespace ‘std’ does not name a template type
       std::array<YGValue, YGEdgeCount> border;
            ^
   |
33 |   std::array<YGValue, YGEdgeCount> border;
   |        ^

yoga/YGStyle.h:34:3: error:
     error: ‘Dimensions’ does not name a type
       Dimensions dimensions;
       ^
   |
34 |   Dimensions dimensions;
   |   ^

yoga/YGStyle.h:35:3: error:
     error: ‘Dimensions’ does not name a type
       Dimensions minDimensions;
       ^
   |
35 |   Dimensions minDimensions;
   |   ^

yoga/YGStyle.h:36:3: error:
     error: ‘Dimensions’ does not name a type
       Dimensions maxDimensions;
       ^
   |
36 |   Dimensions maxDimensions;
   |   ^

yoga/YGStyle.h:46:16: error:
     warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
       ~YGStyle() = default;
                    ^
   |
46 |   ~YGStyle() = default;
   |                ^

<command-line>:0:9: error:
     warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11

yoga/YGNode.h:17:20: error:
     note: in expansion of macro ‘nullptr’
       void* context_ = nullptr;
                        ^
   |
17 |   void* context_ = nullptr;
   |                    ^

<command-line>:0:9: error:
     warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11

yoga/YGNode.h:18:24: error:
     note: in expansion of macro ‘nullptr’
       YGPrintFunc print_ = nullptr;
                            ^
   |
18 |   YGPrintFunc print_ = nullptr;
   |                        ^

In file included from yoga/Utils.h:9:0: error:
    0,
                     from yoga/Utils.cpp:8:

yoga/YGNode.h:19:24: error:
     warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
       bool hasNewLayout_ = true;
                            ^
   |
19 |   bool hasNewLayout_ = true;
   |                        ^

yoga/YGNode.h:20:26: error:
     warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
       YGNodeType nodeType_ = YGNodeTypeDefault;
                              ^
   |
20 |   YGNodeType nodeType_ = YGNodeTypeDefault;
   |                          ^

<command-line>:0:9: error:
     warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11

yoga/YGNode.h:21:28: error:
     note: in expansion of macro ‘nullptr’
       YGMeasureFunc measure_ = nullptr;
                                ^
   |
21 |   YGMeasureFunc measure_ = nullptr;
   |                            ^

<command-line>:0:9: error:
     warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11

yoga/YGNode.h:22:30: error:
     note: in expansion of macro ‘nullptr’
       YGBaselineFunc baseline_ = nullptr;
                                  ^
   |
22 |   YGBaselineFunc baseline_ = nullptr;
   |                              ^

<command-line>:0:9: error:
     warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11

yoga/YGNode.h:23:28: error:
     note: in expansion of macro ‘nullptr’
       YGDirtiedFunc dirtied_ = nullptr;
                                ^
   |
23 |   YGDirtiedFunc dirtied_ = nullptr;
   |                            ^

In file included from yoga/Utils.h:9:0: error:
    0,
                     from yoga/Utils.cpp:8:

yoga/YGNode.h:24:21: error:
     warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
       YGStyle style_ = {};
                         ^
   |
24 |   YGStyle style_ = {};
   |                     ^

yoga/YGNode.h:25:23: error:
     warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
       YGLayout layout_ = {};
                           ^
   |
25 |   YGLayout layout_ = {};
   |                       ^

yoga/YGNode.h:26:25: error:
     warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
       uint32_t lineIndex_ = 0;
                             ^
   |
26 |   uint32_t lineIndex_ = 0;
   |                         ^

<command-line>:0:9: error:
     warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11

yoga/YGNode.h:27:22: error:
     note: in expansion of macro ‘nullptr’
       YGNodeRef owner_ = nullptr;
                          ^
   |
27 |   YGNodeRef owner_ = nullptr;
   |                      ^

In file included from yoga/Utils.h:9:0: error:
    0,
                     from yoga/Utils.cpp:8:

yoga/YGNode.h:28:3: error:
     error: ‘YGVector’ does not name a type
       YGVector children_ = {};
       ^
   |
28 |   YGVector children_ = {};
   |   ^

<command-line>:0:9: error:
     warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11

yoga/YGNode.h:29:25: error:
     note: in expansion of macro ‘nullptr’
       YGConfigRef config_ = nullptr;
                             ^
   |
29 |   YGConfigRef config_ = nullptr;
   |                         ^

In file included from yoga/Utils.h:9:0: error:
    0,
                     from yoga/Utils.cpp:8:

yoga/YGNode.h:30:19: error:
     warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
       bool isDirty_ = false;
                       ^
   |
30 |   bool isDirty_ = false;
   |                   ^

yoga/YGNode.h:31:8: error:
     error: ‘array’ in namespace ‘std’ does not name a template type
       std::array<YGValue, 2> resolvedDimensions_ = {
            ^
   |
31 |   std::array<YGValue, 2> resolvedDimensions_ = {
   |        ^

yoga/YGNode.h:39:14: error:
     warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
       YGNode() = default;
                  ^
   |
39 |   YGNode() = default;
   |              ^

yoga/YGNode.h:40:15: error:
     warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
       ~YGNode() = default; // cleanup of owner/children relationships in YGNodeFree
                   ^
   |
40 |   ~YGNode() = default; // cleanup of owner/children relationships in YGNodeFree
   |               ^

yoga/YGNode.h:42:32: error:
     warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11
       YGNode(const YGNode& node) = default;
                                    ^
   |
42 |   YGNode(const YGNode& node) = default;
   |                                ^

yoga/YGNode.h:110:9: error:
     error: ‘YGVector’ does not name a type
       const YGVector& getChildren() const {
             ^
    |
110 |   const YGVector& getChildren() const {
    |         ^

yoga/YGNode.h:126:8: error:
     error: ‘array’ in namespace ‘std’ does not name a template type
       std::array<YGValue, 2> getResolvedDimensions() const {
            ^
    |
126 |   std::array<YGValue, 2> getResolvedDimensions() const {
    |        ^

yoga/YGNode.h:218:26: error:
     error: ‘YGVector’ does not name a type
       void setChildren(const YGVector& children) {
                              ^
    |
218 |   void setChildren(const YGVector& children) {
    |                          ^

yoga/YGNode.h:15:8: error:
     error: constructor required before non-static data member for ‘YGNode::context_’ has been parsed
     struct YGNode {
            ^
   |
15 | struct YGNode {
   |        ^

yoga/YGNode.h:15:8: error:
     error: constructor required before non-static data member for ‘YGNode::print_’ has been parsed
   |
15 | struct YGNode {
   |        ^

yoga/YGNode.h:15:8: error:
     error: constructor required before non-static data member for ‘YGNode::hasNewLayout_’ has been parsed
   |
15 | struct YGNode {
   |        ^

yoga/YGNode.h:15:8: error:
     error: constructor required before non-static data member for ‘YGNode::nodeType_’ has been parsed
   |
15 | struct YGNode {
   |        ^

yoga/YGNode.h:15:8: error:
     error: constructor required before non-static data member for ‘YGNode::measure_’ has been parsed
   |
15 | struct YGNode {
   |        ^

yoga/YGNode.h:15:8: error:
     error: constructor required before non-static data member for ‘YGNode::baseline_’ has been parsed
   |
15 | struct YGNode {
   |        ^

yoga/YGNode.h:15:8: error:
     error: constructor required before non-static data member for ‘YGNode::dirtied_’ has been parsed
   |
15 | struct YGNode {
   |        ^

yoga/YGNode.h:15:8: error:
     error: constructor required before non-static data member for ‘YGNode::style_’ has been parsed
   |
15 | struct YGNode {
   |        ^

yoga/YGNode.h:15:8: error:
     error: constructor required before non-static data member for ‘YGNode::layout_’ has been parsed
   |
15 | struct YGNode {
   |        ^

yoga/YGNode.h:15:8: error:
     error: constructor required before non-static data member for ‘YGNode::lineIndex_’ has been parsed
   |
15 | struct YGNode {
   |        ^

yoga/YGNode.h:15:8: error:
     error: constructor required before non-static data member for ‘YGNode::owner_’ has been parsed
   |
15 | struct YGNode {
   |        ^

yoga/YGNode.h:15:8: error:
     error: constructor required before non-static data member for ‘YGNode::config_’ has been parsed
   |
15 | struct YGNode {
   |        ^

yoga/YGNode.h:15:8: error:
     error: constructor required before non-static data member for ‘YGNode::isDirty_’ has been parsed
   |
15 | struct YGNode {
   |        ^
yoga/YGNode.h: In member function ‘YGNode* YGNode::getChild(uint32_t) const’:

yoga/YGNode.h:115:12: error:
     error: ‘children_’ was not declared in this scope
         return children_.at(index);
                ^
    |
115 |     return children_.at(index);
    |            ^
yoga/YGNode.h: In member function ‘YGValue YGNode::getResolvedDimension(int) const’:

yoga/YGNode.h:131:12: error:
     error: ‘resolvedDimensions_’ was not declared in this scope
         return resolvedDimensions_[index];
                ^
    |
131 |     return resolvedDimensions_[index];
    |            ^
yoga/YGNode.h: In member function ‘void YGNode::setChildren(const int&)’:

yoga/YGNode.h:219:5: error:
     error: ‘children_’ was not declared in this scope
         children_ = children;
         ^
    |
219 |     children_ = children;
    |     ^

In file included from yoga/Utils.cpp:8:0: error: 
yoga/Utils.h: At global scope:

yoga/Utils.h:84:16: error:
     error: ‘array’ in namespace ‘std’ does not name a template type
         const std::array<float, size>& val1,
                    ^
   |
84 |     const std::array<float, size>& val1,
   |                ^

yoga/Utils.h:84:21: error:
     error: expected ‘,’ or ‘...’ before ‘<’ token
         const std::array<float, size>& val1,
                         ^
   |
84 |     const std::array<float, size>& val1,
   |                     ^
yoga/Utils.h: In function ‘bool YGFloatArrayEqual(int)’:

yoga/Utils.h:88:30: error:
     error: ‘val1’ was not declared in this scope
         areEqual = YGFloatsEqual(val1[i], val2[i]);
                                  ^
   |
88 |     areEqual = YGFloatsEqual(val1[i], val2[i]);
   |                              ^

yoga/Utils.h:88:39: error:
     error: ‘val2’ was not declared in this scope
         areEqual = YGFloatsEqual(val1[i], val2[i]);
                                           ^
   |
88 |     areEqual = YGFloatsEqual(val1[i], val2[i]);
   |                                       ^
`gcc' failed in phase `C Compiler'. (Exit code: 1)

```

Going to set an upper bound for this version and see if `yoga-0.0.0.3` compiles in the meantime.

UPD: seems like the issue also happens with `yoga-0.0.0.3`.

Here's the error for `yoga-0.0.0.3`:

```
Preprocessing library for yoga-0.0.0.3..
Building library for yoga-0.0.0.3..
[1 of 3] Compiling Bindings.Yoga    ( dist/build/Bindings/Yoga.hs, dist/build/Bindings/Yoga.o )
[2 of 3] Compiling Bindings.Yoga.Enums ( dist/build/Bindings/Yoga/Enums.hs, dist/build/Bindings/Yoga/Enums.o )
[3 of 3] Compiling Yoga             ( lib/Yoga.hs, dist/build/Yoga.o )

In file included from /usr/include/c++/5/array:35:0: error:
    0,
                     from yoga/Yoga-internal.h:10,
                     from yoga/YGConfig.h:9,
                     from yoga/YGNode.h:10,
                     from yoga/Utils.h:9,
                     from yoga/Utils.cpp:8:

/usr/include/c++/5/bits/c++0x_warning.h:32:2: error:
     error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
     #error This file requires compiler and library support \
      ^
   |
32 | #error This file requires compiler and library support \
   |  ^

In file included from yoga/Utils.h:9:0: error:
    0,
                     from yoga/Utils.cpp:8:

yoga/YGNode.h:12:21: error:
     fatal error: YGStyle.h: No such file or directory
   |
12 | #include "YGStyle.h"
   |                     ^
compilation terminated.
`gcc' failed in phase `C Compiler'. (Exit code: 1)
```

**Comment by Mokosha** [comment]
Yes, `yoga-0.0.0.3` was a mistake that spurred `yoga-0.0.0.4`.

What version of `gcc` is this? Mine builds with `gcc-7.3.0`. I didn't pass the `-std=c++11` flag earlier because older versions of `gcc` don't support it.

**Comment by Mokosha** [comment]
I uploaded `yoga-0.0.0.5` which uses `cc-options: -std=c++11`. This fails on OS X by default because the Apple compiler doesn't support that flag when compiling C files. It will work if you [specify `gcc`](https://stackoverflow.com/questions/20349104/using-gcc-instead-of-clang-in-ghci-or-ghc) as the compiler for `ghc`, though.

**Comment by Mokosha** [comment]
Also, do you have a link to the build server output by any chance?

**Comment by alexeyzab** [comment]
The `gcc` version on the build server is rather old (5.4.0), I'll look into updating it and see if this fixes the issue. Thanks!

**Comment by alexeyzab** [comment]
Can't link the build server output, unfortunately, but looks like updating to `gcc-7` solved the build failure. `yoga-0.0.5` should be included in `nightly-2018-10-13`. Thanks again!
